<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="2" failures="2" disabled="0" errors="0" timestamp="2020-04-22T11:37:20" time="0.002" name="AllTests">
  <testsuite name="AddFunc" tests="1" failures="1" disabled="0" errors="0" time="0">
    <testcase name="addFuncTest" status="run" time="0" classname="AddFunc">
      <failure message="d:\install\jenkins\workspace\test\gtest_2017_3\gtest_2017_3.cpp:27&#x0A;      Expected: 3&#x0A;To be equal to: sum_2&#x0A;      Which is: 5" type=""><![CDATA[d:\install\jenkins\workspace\test\gtest_2017_3\gtest_2017_3.cpp:27
      Expected: 3
To be equal to: sum_2
      Which is: 5]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="subtract" tests="1" failures="1" disabled="0" errors="0" time="0.001">
    <testcase name="subtractFunctest" status="run" time="0.001" classname="subtract">
      <failure message="d:\install\jenkins\workspace\test\gtest_2017_3\gtest_2017_3.cpp:38&#x0A;      Expected: 5&#x0A;To be equal to: sum_5&#x0A;      Which is: -5" type=""><![CDATA[d:\install\jenkins\workspace\test\gtest_2017_3\gtest_2017_3.cpp:38
      Expected: 5
To be equal to: sum_5
      Which is: -5]]></failure>
    </testcase>
  </testsuite>
</testsuites>
